#ReplicaSet básico:
#   Crea un ReplicaSet con nginx que tenga 2 réplicas.
#   Verifica con kubectl get pods que se levantan.
#   Borra uno de los Pods y observa cómo Kubernetes lo recrea.

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mi-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80