#Pods personalizados dentro de un RS:
#   Crea un ReplicaSet que levante Pods con 2 contenedores:
#   Uno con nginx.
#   Otro con busybox ejecutando echo "Hola desde sidecar" && sleep 3600.
#   Verifica con kubectl logs -c busybox <pod> que el contenedor extra funciona.

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mi-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

        - name: busy
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              while true; do echo "Hola desde sidecar"; sleep 3600; done