#Actualización de versión (Rolling Update):
#   Cambia la imagen de nginx:latest a nginx:1.19.
#   Observa con kubectl rollout status cómo Kubernetes hace el update sin downtime.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.1
          ports:
            - containerPort: 80