apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-1
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-2
spec:
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-3
spec:
  selector:
    app: nginx
  ports:
    - port: 8888
      targetPort: 80
  type: LoadBalancer
