#Crea un Deployment básico:
#   Imagen: nginx:latest
#   Réplicas: 3
#   Puerto expuesto: 80
#   Comprueba que los Pods se crean correctamente.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80