#Sidecar proxy simple
# Un contenedor principal expone :8080.
# Haz un sidecar que escuche en :80 y redirija tráfico hacia localhost:8080.
#   Puedes usar busybox nc -lp 80 -e "nc localhost 8080".

apiVersion: v1
kind: Pod
metadata:
  name: pod

spec:
  containers:
    - name: app
      image: nginx
      ports:
        - containerPort: 8080
      # Cambiar el puerto por defecto de Nginx a 8080
      args: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
      env:
        - name: NGINX_PORT
          value: "8080"

    - name: proxy
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          echo "Proxy escuchando en 80 y redirigiendo a localhost:8080..."
          while true; do
            nc -lp 80 -e nc 127.0.0.1 8080
          done
      ports:
        - containerPort: 80