#Autoscaling manual con ReplicaSet:
#   Crea un ReplicaSet con 3 Pods nginx.
#   Escálalo con el comando: kubectl scale rs <nombre> --replicas=6

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mi-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80