#Recrear Pods eliminados:
#   Borra manualmente un Pod del Deployment con kubectl delete pod.
#   Verifica que el ReplicaSet lo recrea automáticamente.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-c
          image: nginx
          ports:
            - containerPort: 80