apiVersion: v1
kind: Pod
metadata:
  name: pod4-lab

spec:
  containers:
  - name: lab4-container
    image: python:3
    command: ["sh", "-c"]
    args: 
      - |
        sleep 20;
        python -m http.server 8080;
    ports:
    - containerPort: 8080

    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 1
      periodSeconds: 5